# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c355a2d0c0dd5e0a3db9732547a84bfd6fe49b563df46957aee8fcf40cbf6e05721fdbcf12ac61ea7310fd90a990429405473198c50e6c0a6bdba17f7dcd87

test:
  secret_key_base: a99fb75c43f44264e1d85fba45a8db7ca710e26c26f69cd71a113c283a5705728e20d057f5fafbb13fdb6c46b26382b35d80cc6cb01ed06acf9e2eb984c1ad35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
